name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-10.15
          - ubuntu-20.04
          - windows-2019
        ghc:
          - 9.0.1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal configure --enable-tests --flags pedantic --jobs --test-show-details direct
      - run: cabal freeze --minimize-conflict-set
      - run: cat cabal.project.freeze
      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ matrix.os }}-${{ matrix.ghc }}-
      - run: cabal build
      - run: cabal test
      - run: cabal check
