name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        include:
          - { ghc: 9.0.1, os: macos-11 }
          - { ghc: 9.0.1, os: ubuntu-20.04 }
          - { ghc: 9.0.1, os: windows-2019, exe: .exe }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal configure --enable-tests --flags pedantic --jobs --test-show-details direct
      - run: cabal freeze --minimize-conflict-set
      - run: cat cabal.project.freeze
      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ matrix.os }}-${{ matrix.ghc }}-
      - run: cabal build
      - run: cabal test
      - run: cabal check
      - run: mkdir artifact
      - run: mkdir artifact/${{ matrix.os }}
      - run: cabal install --install-method copy --installdir artifact/${{ matrix.os }}
      - uses: svenstaro/upx-action@v2
        with:
          file: artifact/${{ matrix.os }}/monadoc${{ matrix.exe }}
          args: --best
      - uses: actions/upload-artifact@v2
        with:
          path: artifact
